name: Publish Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install --global can-npm-publish
      - run: can-npm-publish --verbose && npm publish --access public || true
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@mazgi-sandbox"
      - run: |
          cat package.json | jq '.name="npm.tiny"' > package.gpr.json
          mv package.gpr.json package.json
      - run: |
          cat package.json | jq '.publishConfig.registry="https://npm.pkg.github.com/"' > package.gpr.json
          mv package.gpr.json package.json
      - run: npm install --global can-npm-publish
      - run: can-npm-publish --verbose && npm publish --access public || true
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
